# Reading POSCAR file

lets see hows the poscar looked like

![image](poscar.jpg)

In [1]:
import numpy as np

In [2]:
def read_poscar(file_name):

    data = open(file_name, "r")

    lines = data.readlines()

    # store the scale
    scale = float(lines[1])
    print("scaling factor: ", scale,'\n')

    # storing arrays of positions in a list

    positions_arrays = []

    for i in range(3):

        # extracting the single array position
        a = []
        for j in lines[i+2].split():
            a.append(j)
        # append the positions of single array
        positions_arrays.append(a)
    

    # now we a list corresponding to the positions
    positions_arrays = np.array(positions_arrays)

    print("position vectors -> ",'\n',positions_arrays)


    # reading the types of atoms that is on the line 6th 
    atoms_types = lines[5].split()
    print('\n',"types of atoms present in the system ", atoms_types)


    # for reading the number of atoms of particular type 
    # creating an empty dictionary   
    atoms_types_count = {}
    for i in atoms_types:      
        j=0  
        atoms_types_count[i] = (lines[6].split()[j])
        j+=1
    print('\n',"types and count of atoms ", atoms_types_count)

    list_atoms_count = []

    
    for i in lines[6].split():
        list_atoms_count.append(int(i))

    print('\n','list of count', list_atoms_count)

    list_atoms_count = np.array(list_atoms_count)
    total_atoms_present_in_system = sum(list_atoms_count)

    print('\n','total_atoms_present_in_system ->', total_atoms_present_in_system)


    # now checking which coordinates are in this system cartesian or direct system

    direct_or_cartesian_system = lines[7].split()[0]
    direct_or_cartesian_system = direct_or_cartesian_system.lower()

    print('\n','type of system present :-> ',direct_or_cartesian_system)


    # to store the coordinates make a list
    coordinates = []

    # to store the atoms in the cartesian system
    atoms = []

    curr_line = 8

    for i in range(len(atoms_types)):
        atoms_symbol = atoms_types[i]
        atoms_symbol_count = list_atoms_count[i]

        for j in range(atoms_symbol_count):
            coordi = [float(val) for val in lines[curr_line].split()]
            curr_line += 1
            coordinates.append(coordi)
            atoms.append(atoms_symbol)

    

    coordinates = np.array(coordinates)
    print(coordinates.shape)
    print(coordinates)

    atoms = np.array(atoms)
    print(atoms.shape)
    print(atoms)

    print(type(positions_arrays))
    print(type(coordinates))

    print(positions_arrays.shape)



    data.close()



In [3]:
read_poscar('POSCAR')

scaling factor:  1.0 

position vectors ->  
 [['4.8606332700000001' '0.0000000000000000' '0.0000000000000000']
 ['0.0000000000000000' '5.8855014600000004' '0.0000000000000000']
 ['0.0000000000000000' '0.0000000000000000' '9.9141976300000003']]

 types of atoms present in the system  ['Fe', 'P', 'O']

 types and count of atoms  {'Fe': '4', 'P': '4', 'O': '4'}

 list of count [4, 4, 16]

 total_atoms_present_in_system -> 24

 type of system present :->  cartesian
(24, 3)
[[2.19157691 4.4141261  7.67414416]
 [0.23873972 4.4141261  2.71704535]
 [2.66905636 1.47137537 2.24005347]
 [4.62189355 1.47137537 7.19715228]
 [4.38122415 4.4141261  5.88720918]
 [2.90972576 4.4141261  0.93011036]
 [0.47940912 1.47137537 4.02698845]
 [1.95090751 1.47137537 8.98408727]
 [1.02640535 4.4141261  6.14997507]
 [1.40391129 4.4141261  1.19287626]
 [3.83422792 1.47137537 3.76422256]
 [3.45672198 1.47137537 8.72132137]
 [3.1744164  4.4141261  9.34692707]
 [4.1165335  4.4141261  4.38982826]
 [1.68621687 1.471375

In [4]:
def read_poscar(file_name):

    data = open(file_name, "r")
    

    lines = data.readlines()
    data.close()

    # store the scale
    scale = float(lines[1])
    print("scaling factor: ", scale,'\n')

    # storing arrays of positions in a list

    positions_arrays = []

    for i in range(3):

        # extracting the single array position
        a = []
        for j in lines[i+2].split():
            a.append(j)
        # append the positions of single array
        positions_arrays.append(a)
    

    # now we a list corresponding to the positions
    positions_arrays = np.array(positions_arrays)


    print("position vectors -> ",'\n',positions_arrays)

    a1 = [float(val) for val in lines[2].split()]
    a2 = [float(val) for val in lines[3].split()]
    a3 = [float(val) for val in lines[4].split()]

    pos_vec = np.array([a1,a2,a3])
    pos_vec = scale * pos_vec


    # reading the types of atoms that is on the line 6th 
    atoms_types = lines[5].split()
    print('\n',"types of atoms present in the system ", atoms_types)


    # for reading the number of atoms of particular type 
    # creating an empty dictionary   
    atoms_types_count = {}
    for i in atoms_types:      
        j=0  
        atoms_types_count[i] = (lines[6].split()[j])
        j+=1
    print('\n',"types and count of atoms ", atoms_types_count)

    list_atoms_count = []

    
    for i in lines[6].split():
        list_atoms_count.append(int(i))

    print('\n','list of count', list_atoms_count)

    list_atoms_count = np.array(list_atoms_count)
    total_atoms_present_in_system = sum(list_atoms_count)

    print('\n','total_atoms_present_in_system ->', total_atoms_present_in_system)


    # now checking which coordinates are in this system cartesian or direct system

    direct_or_cartesian_system = lines[7].split()[0]
    direct_or_cartesian_system = direct_or_cartesian_system.lower()

    print('\n','type of system present :-> ',direct_or_cartesian_system)


    # to store the coordinates make a list
    coordinates = []

    # to store the atoms in the cartesian system
    atoms = []

    curr_line = 8

    for i in range(len(atoms_types)):
        atoms_symbol = atoms_types[i]
        atoms_symbol_count = list_atoms_count[i]

        for j in range(atoms_symbol_count):
            coordi = [float(val) for val in lines[curr_line].split()]
            curr_line += 1
            coordinates.append(coordi)
            atoms.append(atoms_symbol)

    

    coordinates = np.array(coordinates)
    print(coordinates.shape)
    print(coordinates)

    atoms = np.array(atoms)
    print(atoms.shape)
    print(atoms)

    print(type(positions_arrays))
    print(type(coordinates))

    print(positions_arrays.shape)

    print(type(pos_vec))

    print(pos_vec)

    if "d" == direct_or_cartesian_system[0]:
        direct_system = coordinates
        cartesian_system = np.matmul(direct_system,pos_vec)
    else:
        cartesian_system = scale * coordinates
        direct_system = np.matmul(cartesian_system, np.linalg.inv(pos_vec))

    
    

    print('\n', " direct system =", direct_system)
    print('\n', " cartesian system =", cartesian_system)


    data= {'cartesian_system' : cartesian_system,
                 'direct_system': direct_system,
                 'position_vector' : pos_vec,
                 'atoms' : atoms
                 } 
    return data


cartesian_system = direct_system * positions_vector

In [5]:
read_poscar('POSCAR')

scaling factor:  1.0 

position vectors ->  
 [['4.8606332700000001' '0.0000000000000000' '0.0000000000000000']
 ['0.0000000000000000' '5.8855014600000004' '0.0000000000000000']
 ['0.0000000000000000' '0.0000000000000000' '9.9141976300000003']]

 types of atoms present in the system  ['Fe', 'P', 'O']

 types and count of atoms  {'Fe': '4', 'P': '4', 'O': '4'}

 list of count [4, 4, 16]

 total_atoms_present_in_system -> 24

 type of system present :->  cartesian
(24, 3)
[[2.19157691 4.4141261  7.67414416]
 [0.23873972 4.4141261  2.71704535]
 [2.66905636 1.47137537 2.24005347]
 [4.62189355 1.47137537 7.19715228]
 [4.38122415 4.4141261  5.88720918]
 [2.90972576 4.4141261  0.93011036]
 [0.47940912 1.47137537 4.02698845]
 [1.95090751 1.47137537 8.98408727]
 [1.02640535 4.4141261  6.14997507]
 [1.40391129 4.4141261  1.19287626]
 [3.83422792 1.47137537 3.76422256]
 [3.45672198 1.47137537 8.72132137]
 [3.1744164  4.4141261  9.34692707]
 [4.1165335  4.4141261  4.38982826]
 [1.68621687 1.471375

{'cartesian_system': array([[2.19157691, 4.4141261 , 7.67414416],
        [0.23873972, 4.4141261 , 2.71704535],
        [2.66905636, 1.47137537, 2.24005347],
        [4.62189355, 1.47137537, 7.19715228],
        [4.38122415, 4.4141261 , 5.88720918],
        [2.90972576, 4.4141261 , 0.93011036],
        [0.47940912, 1.47137537, 4.02698845],
        [1.95090751, 1.47137537, 8.98408727],
        [1.02640535, 4.4141261 , 6.14997507],
        [1.40391129, 4.4141261 , 1.19287626],
        [3.83422792, 1.47137537, 3.76422256],
        [3.45672198, 1.47137537, 8.72132137],
        [3.1744164 , 4.4141261 , 9.34692707],
        [4.1165335 , 4.4141261 , 4.38982826],
        [1.68621687, 1.47137537, 0.56727056],
        [0.74409977, 1.47137537, 5.52436937],
        [3.65902154, 5.61356187, 6.61384055],
        [3.63192837, 3.21469032, 1.65674174],
        [1.20161173, 2.67081114, 3.30035708],
        [1.2287049 , 0.27193959, 8.25745589],
        [1.20161173, 0.27193959, 3.30035708],
        [1.228

# writing xyz coordinates file

![image](xyz.jpg)

In [6]:
data = read_poscar('POSCAR')
for i in range(len(data['atoms'])):
    print(data['atoms'][i],  data['direct_system'][i], data['cartesian_system'][i])

scaling factor:  1.0 

position vectors ->  
 [['4.8606332700000001' '0.0000000000000000' '0.0000000000000000']
 ['0.0000000000000000' '5.8855014600000004' '0.0000000000000000']
 ['0.0000000000000000' '0.0000000000000000' '9.9141976300000003']]

 types of atoms present in the system  ['Fe', 'P', 'O']

 types and count of atoms  {'Fe': '4', 'P': '4', 'O': '4'}

 list of count [4, 4, 16]

 total_atoms_present_in_system -> 24

 type of system present :->  cartesian
(24, 3)
[[2.19157691 4.4141261  7.67414416]
 [0.23873972 4.4141261  2.71704535]
 [2.66905636 1.47137537 2.24005347]
 [4.62189355 1.47137537 7.19715228]
 [4.38122415 4.4141261  5.88720918]
 [2.90972576 4.4141261  0.93011036]
 [0.47940912 1.47137537 4.02698845]
 [1.95090751 1.47137537 8.98408727]
 [1.02640535 4.4141261  6.14997507]
 [1.40391129 4.4141261  1.19287626]
 [3.83422792 1.47137537 3.76422256]
 [3.45672198 1.47137537 8.72132137]
 [3.1744164  4.4141261  9.34692707]
 [4.1165335  4.4141261  4.38982826]
 [1.68621687 1.471375

In [34]:
def write_xyz_file(file_name , data):

    file = open(file_name,"w")
    file.write("%d \n" % (len(data['cartesian_system'])))
    print(len(data['cartesian_system']))
    

    a1 = " ".join([str(x) for x in data['position_vector'][0]])
    a2 = " ".join([str(x) for x in data['position_vector'][1]])
    a3 = " ".join([str(x) for x in data['position_vector'][2]])

    print("Lattice=",'"',a1, a2, a3,'"')

    file.write('Lattice="%s %s %s"' % (a1,a2,a3))

    
    for i in range(len(data['cartesian_system'])):
        
        
        print(data['atoms'][i], data['cartesian_system'][i][0],
                                       data['cartesian_system'][i][1],
                                       data['cartesian_system'][i][2])
        
        file.write("%s %f %f %f \n" % (data['atoms'][i], data['cartesian_system'][i][0],
                                       data['cartesian_system'][i][1],
                                       data['cartesian_system'][i][2]))
    

    


In [35]:
write_xyz_file('test.xyz' , data)

24
Lattice= " 4.86063327 0.0 0.0 0.0 5.88550146 0.0 0.0 0.0 9.91419763 "
Fe 2.19157691067741 4.414126095 7.67414416068728
Fe 0.23873972432259 4.414126095 2.7170453456872803
Fe 2.6690563593225898 1.471375365 2.2400534693127203
Fe 4.62189354567741 1.471375365 7.197152284312721
P 4.38122414994663 4.414126095 5.887209179856081
P 2.9097257550533704 4.414126095 0.93011036485608
P 0.47940912005337 1.471375365 4.02698845014392
P 1.95090751494663 1.471375365 8.98408726514392
O 1.02640534572609 4.414126095 6.1499750738416
O 1.40391128927391 4.414126095 1.1928762588416
O 3.83422792427391 1.471375365 3.7642225561584004
O 3.45672198072609 1.471375365 8.7213213711584
O 3.17441640040449 4.414126095 9.346927070006661
O 4.11653350459551 4.414126095 4.38982825500666
O 1.6862168695955102 1.471375365 0.56727055999334
O 0.7440997654044901 1.471375365 5.5243693749933405
O 3.65902153742349 5.6135618650407 6.6138405525540405
O 3.6319283675765104 3.2146903249593004 1.65674173755404
O 1.2016117325765099 2.67081