Python functionalities developed by same/other users can be used easily in other codes using modules. Python modules allow user to logically organise their code for distribution/ use in other programs.

Previously developed/installed/downloaded modules can be used in a current code using a `import` keyword. Some of the usages are:

### Usage 1: (not recommended) [import everything from numpy]

In [1]:
from numpy import * 
from matplotlib import *
a = zeros([10,10])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Usage 2: (recommended)

In [ ]:
import numpy
a = numpy.zeros([10,10])
print(a)

### Usage 3: 

In [ ]:
import numpy as np
a = np.zeros([10,10])
print(a)

### Usage 4: 

In [ ]:
from numpy import zeros
a = zeros([10,10])
print(a)

### Usage 5: 

In [ ]:
from numpy import zeros as myzeros
a = myzeros([10,10])
print(a)

## Some useful modules/libraries:
1. [numpy: for linear-algebra/numerical routines](https://www.numpy.org/)
2. [scipy: for curve-fitting/optimization/science related routines](https://www.scipy.org/)
3. [matplotplib: for plotting](https://matplotlib.org/)
4. [scikit-learn (sklearn): for machine learning](https://scikit-learn.org/stable/)