Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type.

## Array creation
There are several ways to create an array using numpy:

In [1]:
import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

[2 3 4]
int64
[1.2 3.5 5.1]
float64


In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

In [ ]:
c = np.array( [ [1,1+2j], [3,4] ], dtype=complex )
print(c)

In [2]:
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
a = np.ones([3,4], dtype='int64')
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
a  = np.arange( 10, 30, 5 )
print(a)

[10 15 20 25]


In [5]:
a = np.linspace( 0, 2, 9 )
print(a)
b = np.random.random((2,3))
print(b)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[0.57657521 0.06738613 0.44341048]
 [0.39169941 0.83332079 0.60913012]]


In [6]:
def f(x,y):
    return 10**x+y
print(np.fromfunction(f,(5,4)))

[[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00]
 [1.0000e+01 1.1000e+01 1.2000e+01 1.3000e+01]
 [1.0000e+02 1.0100e+02 1.0200e+02 1.0300e+02]
 [1.0000e+03 1.0010e+03 1.0020e+03 1.0030e+03]
 [1.0000e+04 1.0001e+04 1.0002e+04 1.0003e+04]]


## Array Operations
Arithmetic operators on arrays apply elementwise.

In [7]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [8]:
np.sin?

In [9]:
print(10*np.sin(a))

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [10]:
print(a<35)

[ True  True False False]


In [11]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A*B)
print(np.matmul(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


__Notice__ the difference here between elementwise and matrixwise operations.

In [12]:
a = np.ones((2,3))
b = np.random.random((2,3))
print(3*a)
print(b)
b += 3*a
print(b)

[[3. 3. 3.]
 [3. 3. 3.]]
[[0.63486854 0.35519271 0.55486683]
 [0.28249351 0.79490945 0.62931061]]
[[3.63486854 3.35519271 3.55486683]
 [3.28249351 3.79490945 3.62931061]]


## Statistical functions

In [13]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.std(), a.var())

[[0.53611541 0.01147225 0.84044977]
 [0.03313485 0.14106122 0.64058385]]
2.202817342864332
0.011472252299654762
0.8404497702615386
0.3205508192468513 0.10275282771982752


In [14]:
b = np.arange(12)
print(b)
b = b.reshape(3,4)
print(b)
print(b.sum(axis=0))
print(b.min(axis=1))
print(a.std(axis=0)) 
print(a.std(axis=1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[0.25149028 0.06479448 0.09993296]
[0.34238925 0.26460983]


In [15]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Indexing, Slicing and Iterating on one-dimensional Numpy arrays

In [16]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
print(a[-3:])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[343 512 729]


In [17]:
print(a)
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; 
                   # from start to position 6, exclusive, set every 2nd element to -1000
print(a)

[  0   1   8  27  64 125 216 343 512 729]
[-1000     1 -1000    27 -1000   125   216   343   512   729]


In [18]:
print(a[ : :-1])                      # reversed a

[  729   512   343   216   125 -1000    27 -1000     1 -1000]


## Indexing, Slicing and Iterating on multi-dimensional Numpy arrays

In [19]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4))
print(b)
print(b[2,3])
print(b[0:5, 1])

[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]
 [30. 31. 32. 33.]
 [40. 41. 42. 43.]]
23.0
[ 1. 11. 21. 31. 41.]


In [20]:
print(b[1:3, : ])

[[10. 11. 12. 13.]
 [20. 21. 22. 23.]]


In [21]:
print(b)
print('-'*80)
for row in b:
    print(row)

[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]
 [30. 31. 32. 33.]
 [40. 41. 42. 43.]]
--------------------------------------------------------------------------------
[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


## Shape Manipulation

In [22]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print('-'*80)
print(a.shape)
print('='*80)

a.resize(6,2)
print(a)
print('-'*80)
print(a.shape)
print('='*80)

print(np.reshape(a, (3,4)))

[[9. 9. 5. 0.]
 [3. 0. 1. 0.]
 [6. 5. 9. 3.]]
--------------------------------------------------------------------------------
(3, 4)
[[9. 9.]
 [5. 0.]
 [3. 0.]
 [1. 0.]
 [6. 5.]
 [9. 3.]]
--------------------------------------------------------------------------------
(6, 2)
[[9. 9. 5. 0.]
 [3. 0. 1. 0.]
 [6. 5. 9. 3.]]


In [ ]:
a.T  # returns the array, transposed

In [ ]:
print(a.T.shape)
print(a.shape)